---
- name: Disk Performance Test with iozone
  hosts: all
  gather_facts: yes
  tasks:
    - name: Make sure that an empty requirements.yml file exists
      delegate_to: 127.0.0.1
      file:
        path: requirements.yml
        state: touch

    - name: Create requirements.yml
      delegate_to: 127.0.0.1
      blockinfile:
        path: requirements.yml
        create: yes
        block: |
          ---
          # Install a role from GitHub
          - src: https://github.com/joschro/ansible-role-rpmfusion
            name: joschro.rpmfusion

    - name: Source required roles
      local_action: command ansible-galaxy install -r requirements.yml --force
      # (add parameter --force to update role on succeeding runs of playbook)

    - name: Execute rpmfusion role
      include_role:
        name: joschro.rpmfusion

    - name: Install iozone
      become: yes
      apt:
        name: iozone3
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install iozone
      become: yes
      yum:
        name: iozone
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Display RAM size
      debug:
        msg: "RAM size on {{ ansible_hostname }} is {{ ansible_memory_mb.real.total }} MB"

    - name: Get RAM size
      set_fact:
        ram_size_mb: "{{ ansible_memtotal_mb }}"

    - name: Set file size to double RAM size
      set_fact:
        iozone_file_size_mb: "{{ ram_size_mb * 2 }}"

    - debug: msg="{{ item.mount }}"
      with_items:
      - "{{ ansible_mounts }}"

    - name: Display disk stats for /
      debug:
        msg: "Available disk space on {{ ansible_hostname }} for {{ item.mount }} is {{ item.size_available }} Byte"
      with_items: 
      - "{{ ansible_mounts }}"
      
    - name: Get available disk space on /
      set_fact:
        disk_free: "{{ ( item.size_available | default(0) | int / 1024 / 1024 ) | int }}"
      loop: "{{ ansible_mounts }}"
      when: item.mount == '/'  # Filtere nach dem / Verzeichnis
      register: disk_space


    - name: Display free space on /
      debug:
        #msg: "Free space on /: {{ ( disk_free / 1024 / 1024) | round(2) }} MB"
        msg: "Free space on /: {{ disk_free }} MB, {{ iozone_file_size_mb }} MB needed for testing"

        #    - name: Abort playbook if free space is less than iozone file size
        #      fail:
        #        msg: "Not enough free space on / to run iozone test."
        #      when: (disk_free | int) < (iozone_file_size_mb | int)

    - name: Lower iozone_file_size_mb to fit into free disk space
      set_fact:
        iozone_file_size_mb: "{{ (( disk_free | int ) * 0.6 ) | int }}"
      when: (disk_free | int) < (iozone_file_size_mb | int)

    - name: Run iozone test
      debug:
        msg: "command on {{ ansible_hostname }}: iozone -e -I -s {{ iozone_file_size_mb }}m -r 4k -i 0 -i 1 -i 2 -f /iozone_testfile -b /tmp/iozone_testresult.wks"

    - name: Run iozone test
      become: yes
      command: iozone -e -I -s {{ iozone_file_size_mb }}m -r 4k -i 0 -i 1 -i 2 -f /iozone_testfile -b /tmp/iozone_testresult.wks

    - name: Fetch iozone test results
      fetch:
        src: "/tmp/iozone_testresult.wks"
        dest: "{{ playbook_dir }}/iozone_test_results/{{ inventory_hostname }}_{{ ansible_date_time.date }}"

